### ISSUE TITLE
Issue while listing offsprings

### ISSUE THREAD

**Issue by katafira** [propedeutica/lastablas#26] opened 2016-08-10 08:04 UTC
While being logged in as and admin, if one goes to the "Admin" page and afterwords to "Catecúmenos", if one tries to jump to the next listing, from page 1 of Catecúmenos to any other 2,3,4... the site jumps to the parents view instead of listing the rest of Catecúmenos.

@alexvkcr @delaluzparra @sergio-ocon

**Comment by sergio-ocon** [comment] 2016-08-10 09:58
This used to work and now is a regression, it seems to be linked to the fact that the JS is not loading properly

**Comment by katafira** [comment] 2016-08-30 07:57
Can this issue be closed? It has been solved. @sergio-ocon

**Comment by sergio-ocon** [comment] 2016-08-30 08:01
Closing as per request

**Closed by sergio-ocon** 2016-08-30 08:01 UTC
